# Generated by Django 3.0.2 on 2020-02-10 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('offers', '0001_initial'), ('offers', '0002_update_offers')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('location', models.CharField(max_length=50)),
                ('offer_text', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Company')),
                ('offer_title', models.CharField(default='title', max_length=50)),
            ],
        ),
    ]
